apiVersion: apps/v1
kind: Deployment
metadata:
  name: cowsay
  namespace: default
  labels:
    app: demo
spec:
  replicas: 5
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - env:
        - name: COW_COLOR
          value: pink
        name: demo
        image: bgulla/rancher-demo
        ports:
        - containerPort: 8080



---
apiVersion: v1
kind: Service
metadata:
  name: cowsay
  namespace: default
spec:
  selector:
    app: demo
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cowsay
  namespace: default
spec:
  rules:
  - host: cow.rfed.demo.rancher.lol
    http:
      paths:
      - backend:
          service:
            name: cowsay
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - cow.rfed.demo.rancher.lol
    secretName: cow-ingress

